image: Visual Studio 2015   

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\libcommsdsl
shallow_clone: true             

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14

install:
    - call script\appveyor_install.bat

build_script:
    - mkdir build.%PLATFORM%.%CONFIGURATION%
    - cd build.%PLATFORM%.%CONFIGURATION%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DBOOST_ROOT="C:\Libraries\boost_1_65_1" -DBoost_USE_STATIC_LIBS=ON
    - nmake 

test_script:
    - set PATH=%PATH%;c:\projects\libcommsdsl\build.%PLATFORM%.%CONFIGURATION%\src
    - ctest 


